name: check_python_version

on:
  push:
    branches:
      - check_python_version

jobs:
  check-python-version:
    runs-on: ubuntu-latest

    steps:
      - name: ustaw wersje pythona 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Aktualizacja pip
        run: |
          python -m pip install --upgrade pip

      - name: Wyswietlanie wersji pythona
        run: |
          python --version
